version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/browser-kit
    versions:
    - ">= 5.a, < 6"
  - dependency-name: symfony/css-selector
    versions:
    - ">= 5.a, < 6"
  - dependency-name: symfony/dotenv
    versions:
    - ">= 5.a, < 6"
  - dependency-name: symfony/orm-pack
    versions:
    - ">= 2.0.a, < 2.1"
  - dependency-name: symfony/profiler-pack
    versions:
    - "> 1.0.4, < 1.1"
  - dependency-name: symfony/test-pack
    versions:
    - "> 1.0.6, < 1.1"
  - dependency-name: symfony/twig-pack
    versions:
    - "> 1.0.0, < 1.1"
  - dependency-name: symfony/yaml
    versions:
    - ">= 5.a, < 6"
  - dependency-name: doctrine/doctrine-migrations-bundle
    versions:
    - 3.0.2
    - 3.1.0
  - dependency-name: doctrine/doctrine-bundle
    versions:
    - 2.2.3
    - 2.2.4
    - 2.3.0
  - dependency-name: symfony/console
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/webpack-encore-bundle
    versions:
    - 1.11.0
    - 1.11.1
    - 1.9.0
  - dependency-name: symfony/css-selector
    versions:
    - 4.4.19
  - dependency-name: symfony/twig-bundle
    versions:
    - 4.4.19
  - dependency-name: symfony/browser-kit
    versions:
    - 4.4.19
  - dependency-name: symfony/framework-bundle
    versions:
    - 4.4.19
  - dependency-name: twig/twig
    versions:
    - 3.2.1
  - dependency-name: twig/extra-bundle
    versions:
    - 3.2.1
