controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

schedule-controllers:
    resource: ../../proAppointments/Schedule/src/Adapter/In/Web
    type: annotation