doctrine:
    dbal:
        # configure these for your database server
        # use postgresql for PostgreSQL
        # use sqlite for SQLite
#        driver: 'mysql'
#        server_version: '5.7'
#
#        # only needed for MySQL
#        charset: utf8mb4
#        default_table_options:
#            charset: utf8mb4
#            collate: utf8mb4_unicode_ci
#
#        url: '%env(resolve:DATABASE_URL)%'
        types:
            schedule_appointment_id:  ProAppointments\Schedule\Adapter\Out\Persistence\Doctrine\Config\Type\DoctrineAppointmentIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Schedule:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/proAppointments/Schedule/src/Adapter/Out/Persistence/Doctrine/Config/Mapping/xml'
                prefix: 'ProAppointments\Schedule\Domain'
                alias: Schedule
