# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        public: true

    # test.App\Service\MyService: '@App\Service\MyService'

    test.doctrine.dbal.connection: '@Doctrine\DBAL\Connection'

    ProAppointments\IdentityAccess\Tests\DataFixtures\:
        resource: '../../../proAppointments/IdentityAccess/tests/DataFixtures/'
        tags: ['doctrine.fixture.orm']

    test.ProAppointments\IdentityAccess\Infrastructure\DomainService\DomainRegistry: '@ProAppointments\IdentityAccess\Infrastructure\DomainService\DomainRegistry'

    test.ProAppointments\IdentityAccess\Infrastructure\Persistence\Adapter\UserRepositoryAdapter: '@ProAppointments\IdentityAccess\Infrastructure\Persistence\Adapter\UserRepositoryAdapter'

    test.identity.transactional.session: '@identity.transactional.session'

    test.ProAppointments\IdentityAccess\Infrastructure\Factories\ApplicationServiceFactory: '@ProAppointments\IdentityAccess\Infrastructure\Factories\ApplicationServiceFactory'

    test.Identity\Transational\RegisterUserService: '@Identity\Transational\RegisterUserService'
    #test.ProAppointments\IdentityAccess\Application\UserUseCase\RegisterUserService: '@ProAppointments\IdentityAccess\Application\UserUseCase\RegisterUserService'
    #test.ProAppointments\IdentityAccess\Application\UserUseCase\ChangeFirstNameService: '@ProAppointments\IdentityAccess\Application\UserUseCase\ChangeFirstNameService'

    #test.ProAppointments\IdentityAccess\Application\UserUseCase\DeleteUserService: '@ProAppointments\IdentityAccess\Application\UserUseCase\DeleteUserService'

    #test.ProAppointments\IdentityAccess\Application\UserUseCase\ChangePasswordService: '@ProAppointments\IdentityAccess\Application\UserUseCase\ChangePasswordService'
    #ProAppointments\IdentityAccess\Domain\Service\PasswordEncoder: '@ProAppointments\IdentityAccess\Infrastructure\DomainService\NullPasswordEncoder'
    #ProAppointments\IdentityAccess\Infrastructure\DomainService\NullPasswordEncoder:


    #
    #   PERSISTANCE LAYER
    #

    test.ProAppointments\IdentityAccess\Infrastructure\Persistence\Doctrine\DoctrineUserRepository: '@ProAppointments\IdentityAccess\Infrastructure\Persistence\Doctrine\DoctrineUserRepository'
    test.ProAppointments\IdentityAccess\Infrastructure\Persistence\Doctrine\Query\UniqueUserEmailQuery: '@ProAppointments\IdentityAccess\Infrastructure\Persistence\Doctrine\Query\UniqueUserEmailQuery'

    test.ProAppointments\IdentityAccess\Infrastructure\Persistence\Doctrine\DoctrineRoleRepository: '@ProAppointments\IdentityAccess\Infrastructure\Persistence\Doctrine\DoctrineRoleRepository'
    test.ProAppointments\IdentityAccess\Infrastructure\Persistence\Doctrine\Query\RoleQuery: '@ProAppointments\IdentityAccess\Infrastructure\Persistence\Doctrine\Query\RoleQuery'
    test.ProAppointments\IdentityAccess\Infrastructure\Persistence\Doctrine\Query\UniqueRoleNameQuery: '@ProAppointments\IdentityAccess\Infrastructure\Persistence\Doctrine\Query\UniqueRoleNameQuery'