# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:

    ProAppointments\IdentityAccess\Tests\Support\Fixtures\Dev\:
        resource: '../../../proAppointments/IdentityAccess/tests/Support/Fixtures/Dev/'
        tags: ['doctrine.fixture.orm']
