doctrine:
    dbal:
        # configure these for your database server
        # use postgresql for PostgreSQL
        # use sqlite for SQLite
#        driver: 'mysql'
#        server_version: '5.7'
#
#        # only needed for MySQL
#        charset: utf8mb4
#        default_table_options:
#            charset: utf8mb4
#            collate: utf8mb4_unicode_ci
#
#        url: '%env(resolve:DATABASE_URL)%'
        types:
            #user_id:  Humble\Infrastructure\Persistance\Doctrine\config\Type\UserIdDoctrineType
            identity_user_id:  ProAppointments\IdentityAccess\Infrastructure\Persistence\Doctrine\Config\Type\DoctrineUserIdType
            identity_last_name:  ProAppointments\IdentityAccess\Infrastructure\Persistence\Doctrine\Config\Type\DoctrineLastNameType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
#            IdentityAccess:
#                is_bundle: false
#                type: yml
#                dir: '%kernel.project_dir%/proAppointments/IdentityAccess/src/Infrastructure/Persistence/Doctrine/Config/Mapping/yml'
#                prefix: 'ProAppointments\IdentityAccess\Domain'
#                alias: IdentityAccess
            IdentityAccess:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/proAppointments/IdentityAccess/src/Infrastructure/Persistence/Doctrine/Config/Mapping/yml'
                prefix: 'ProAppointments\IdentityAccess'
                alias: IdentityAccess
