name: QA

on:
  push:
    branches: [ master, develop, feature/** ]
  pull_request:
    branches: [ master,develop ]

jobs:
  lint-composer:
    name: Composer lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer:v1, phpstan
          extensions: intl, bcmath, curl, openssl, mbstring
          ini-values: memory_limit=-1
          coverage: none

      - name: QA - Run composer validate
        uses: docker://jakzal/phpqa:php7.4-alpine
        with:
          args: composer validate --strict --ansi
        continue-on-error: false

      - name: QA - Run composer normalize
        uses: docker://jakzal/phpqa:php7.4-alpine
        with:
          args: composer normalize --dry-run
        continue-on-error: false
