name: QA

on:
  push:
    branches: [ master, develop, feature/** ]

  pull_request:
    branches: [ master,develop ]

jobs:
  lint-composer:
    name: Composer lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          tools: composer:v1
          extensions: intl, bcmath, curl, openssl, mbstring
          ini-values: memory_limit=-1
          coverage: none

      -
        name: QA - Run composer validate
        run: composer validate --strict --ansi



  security-check:
    name: Security check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        php:
          - '7.3'
      fail-fast: false
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v1
          extensions: intl, bcmath, curl, openssl, mbstring
          ini-values: memory_limit=-1
          coverage: none

      -
        name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      -
        name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      -
        name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --ansi --no-scripts

      -
        name: QA - Run sensiolab security check
        run: bin/console security:check

      -
        name: QA - Run roave security check
        run: |
          composer require --dev roave/security-advisories:dev-latest
          composer update --dry-run roave/security-advisories
